
name: Continuous Deployment with Docker

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yatawaki-web-admin

    steps:
    - uses: actions/checkout@v2
      name: Cloning Repository
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image
      with:
        image: u201711778/yatawaki-admin
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
