name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests Run
        run: |
          cd yatawaki-web-admin
          npm install
          npm run build
          ng test --browsers ChromeHeadless
