name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests Run
        run: |
          cd yatawaki-web-admin
          npm install
          npm run build
          npm run test:prod
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: yatawaki-web-admin/coverage/yatawaki-web-admin/*
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 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  # Needed to get PR information, if any
          SONAR_TOKEN: 387188bb88889acbea291003197b17c7c3e5e049
